import type { QuantumCalculationResult } from '@/lib/chem/quantumTypes';

export type QuantumExportMetadata = {
  name?: string;
  smiles?: string | null;
  formula?: string | null;
  cid?: string | null;
  pdbId?: string | null;
  fileName?: string | null;
};

export type QuantumExportDocumentContext = {
  charge: number;
  metadata?: QuantumExportMetadata;
  unpairedElectrons: number;
};

const TEXT_ENCODER = new TextEncoder();
const CHEMVAULT_TITLE = 'ChemVault Quantum Calculation Report';
const CHEMVAULT_AUTHOR = 'ChemVault';
const CHEMVAULT_COMPANY = 'ChemVault';
const CHEMVAULT_CREATOR = 'ChemVault Model';
const CHEMVAULT_SUBJECT = 'Quantum calculation results generated by ChemVault Model';
const CHEMVAULT_KEYWORDS = 'ChemVault, quantum calculation, molecule, molecular model';
export const CHEMVAULT_COPYRIGHT_NOTICE =
  'Copyright (c) ChemVault. All rights reserved. ChemVault copyright metadata and footer are fixed by the application and must not be altered.';

type ZipEntry = {
  path: string;
  content: string | Uint8Array;
};

export function createQuantumExcelWorkbook(result: QuantumCalculationResult, context: QuantumExportDocumentContext) {
  const generatedAt = new Date();
  const summaryRows = quantumSummaryRows(result, context, generatedAt);
  const warnings = result.warnings.length ? result.warnings : ['No warnings returned.'];
  const chargeRows = result.charges.map((atom) => [String(atom.index), atom.element, `${formatSigned(atom.charge)} e`]);
  const logLines = logText(result).split(/\r?\n/u);

  const workbook = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <workbookPr/>
  <sheets>
    <sheet name="Summary" sheetId="1" r:id="rId1"/>
    <sheet name="Engine Log" sheetId="2" r:id="rId2"/>
  </sheets>
  <workbookProtection lockStructure="1"/>
</workbook>`;

  const summarySheetRows = [
    ['ChemVault Quantum Calculation Report'],
    ...summaryRows,
    [],
    ['Warnings'],
    ...warnings.map((warning) => [warning]),
    [],
    ['Partial Charges'],
    ['Atom', 'Element', result.chargeModel],
    ...(chargeRows.length ? chargeRows : [['N/A', 'N/A', 'No partial charges returned']]),
    [],
    ['ChemVault Copyright', CHEMVAULT_COPYRIGHT_NOTICE]
  ];
  const logSheetRows = [
    ['ChemVault Quantum Calculation Engine Log'],
    ['Generated', generatedAt.toISOString()],
    ['Copyright', CHEMVAULT_COPYRIGHT_NOTICE],
    [],
    ...logLines.map((line) => [line])
  ];

  return createZip([
    { path: '[Content_Types].xml', content: xlsxContentTypes() },
    { path: '_rels/.rels', content: packageRelationships('xlsx') },
    { path: 'docProps/core.xml', content: coreProperties(generatedAt) },
    { path: 'docProps/app.xml', content: appProperties('Microsoft Excel') },
    { path: 'docProps/custom.xml', content: customProperties() },
    { path: 'xl/workbook.xml', content: workbook },
    { path: 'xl/_rels/workbook.xml.rels', content: workbookRelationships() },
    { path: 'xl/worksheets/sheet1.xml', content: worksheetXml(summarySheetRows) },
    { path: 'xl/worksheets/sheet2.xml', content: worksheetXml(logSheetRows) }
  ]);
}

export function createQuantumWordDocument(result: QuantumCalculationResult, context: QuantumExportDocumentContext) {
  const generatedAt = new Date();
  const warnings = result.warnings.length ? result.warnings : ['No warnings returned.'];
  const body = [
    docParagraph(CHEMVAULT_TITLE, true),
    docParagraph(`Generated: ${generatedAt.toLocaleString()}`),
    docParagraph(`Molecule: ${moleculeLabel(context.metadata)}`),
    docParagraph('Calculation Summary', true),
    docTable(quantumSummaryRows(result, context, generatedAt)),
    docParagraph('Computed Properties', true),
    docTable(computedPropertyRows(result)),
    docParagraph('Partial Charges', true),
    docTable([
      ['Atom', 'Element', result.chargeModel],
      ...(result.charges.length
        ? result.charges.map((atom) => [String(atom.index), atom.element, `${formatSigned(atom.charge)} e`])
        : [['N/A', 'N/A', 'No partial charges returned']])
    ]),
    docParagraph('Warnings', true),
    ...warnings.map((warning) => docParagraph(warning)),
    docParagraph('Engine Log', true),
    ...logText(result).split(/\r?\n/u).map((line) => docParagraph(line || ' ')),
    docParagraph(CHEMVAULT_COPYRIGHT_NOTICE, true),
    '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>'
  ].join('');

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>${body}</w:body>
</w:document>`;

  return createZip([
    { path: '[Content_Types].xml', content: docxContentTypes() },
    { path: '_rels/.rels', content: packageRelationships('docx') },
    { path: 'docProps/core.xml', content: coreProperties(generatedAt) },
    { path: 'docProps/app.xml', content: appProperties('Microsoft Word') },
    { path: 'docProps/custom.xml', content: customProperties() },
    { path: 'word/document.xml', content: documentXml },
    { path: 'word/settings.xml', content: wordSettings() },
    { path: 'word/styles.xml', content: wordStyles() }
  ]);
}

export function createQuantumPdfDocument(result: QuantumCalculationResult, context: QuantumExportDocumentContext) {
  const generatedAt = new Date();
  const lines = [
    CHEMVAULT_TITLE,
    `Generated: ${generatedAt.toLocaleString()}`,
    `Molecule: ${moleculeLabel(context.metadata)}`,
    `Engine: ${result.engineLabel}`,
    `Method: ${result.method}`,
    `Calculation mode: ${result.calculationMode}`,
    `Total charge: ${context.charge}`,
    `Unpaired electrons: ${context.unpairedElectrons}`,
    `Status: ${result.ok ? 'Completed' : result.error || 'Not completed'}`,
    '',
    'Computed properties',
    ...computedPropertyRows(result).map((row) => `${row[0]}: ${row[1]}`),
    '',
    'Partial charges',
    ...(result.charges.length
      ? result.charges.map((atom) => `${atom.index}  ${atom.element}  ${formatSigned(atom.charge)} e`)
      : ['No partial charges returned.']),
    '',
    'Warnings',
    ...(result.warnings.length ? result.warnings : ['No warnings returned.']),
    '',
    'Engine log',
    ...logText(result).split(/\r?\n/u),
    '',
    CHEMVAULT_COPYRIGHT_NOTICE
  ].flatMap((line) => wrapPdfLine(line));

  const pageLineCount = 52;
  const pages = [];
  for (let index = 0; index < lines.length; index += pageLineCount) {
    pages.push(lines.slice(index, index + pageLineCount));
  }

  const objects: string[] = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push('');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');

  const pageRefs: string[] = [];
  pages.forEach((pageLines, pageIndex) => {
    const pageObjectId = 4 + pageIndex * 2;
    const contentObjectId = pageObjectId + 1;
    pageRefs.push(`${pageObjectId} 0 R`);
    objects[pageObjectId - 1] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObjectId} 0 R >>`;
    const content = [
      'BT',
      '/F1 10 Tf',
      '12 TL',
      '50 770 Td',
      ...pageLines.map((line) => `(${escapePdf(line)}) Tj T*`),
      'ET'
    ].join('\n');
    objects[contentObjectId - 1] = `<< /Length ${byteLength(content)} >>\nstream\n${content}\nendstream`;
  });

  objects[1] = `<< /Type /Pages /Kids [${pageRefs.join(' ')}] /Count ${pages.length} >>`;
  const infoObjectId = objects.length + 1;
  objects.push(`<< /Title (${escapePdf(CHEMVAULT_TITLE)}) /Author (${escapePdf(CHEMVAULT_AUTHOR)}) /Subject (${escapePdf(CHEMVAULT_SUBJECT)}) /Keywords (${escapePdf(CHEMVAULT_KEYWORDS)}) /Creator (${escapePdf(CHEMVAULT_CREATOR)}) /Producer (${escapePdf(CHEMVAULT_CREATOR)}) /CreationDate (${pdfDate(generatedAt)}) /ModDate (${pdfDate(generatedAt)}) /Copyright (${escapePdf(CHEMVAULT_COPYRIGHT_NOTICE)}) >>`);

  return buildPdf(objects, infoObjectId);
}

function quantumSummaryRows(result: QuantumCalculationResult, context: QuantumExportDocumentContext, generatedAt: Date) {
  return [
    ['Generated', generatedAt.toISOString()],
    ['Molecule', moleculeLabel(context.metadata)],
    ['Engine', result.engineLabel],
    ['Method', result.method],
    ['Calculation mode', result.calculationMode],
    ['Total charge', String(context.charge)],
    ['Unpaired electrons', String(context.unpairedElectrons)],
    ['Status', result.ok ? 'Completed' : result.error || 'Not completed']
  ];
}

function computedPropertyRows(result: QuantumCalculationResult) {
  return [
    ['Total energy', result.energyHartree === null ? 'N/A' : `${formatNumber(result.energyHartree)} Eh`],
    ['Dipole magnitude', result.dipoleDebye ? `${formatNumber(result.dipoleDebye.total)} D` : 'N/A'],
    ['Dipole X', result.dipoleDebye ? `${formatSigned(result.dipoleDebye.x)} D` : 'N/A'],
    ['Dipole Y', result.dipoleDebye ? `${formatSigned(result.dipoleDebye.y)} D` : 'N/A'],
    ['Dipole Z', result.dipoleDebye ? `${formatSigned(result.dipoleDebye.z)} D` : 'N/A'],
    ['Partial charges', String(result.charges.length)],
    ['Charge model', result.chargeModel],
    ['Elapsed time', `${(result.elapsedMs / 1000).toFixed(1)} s`]
  ];
}

function moleculeLabel(metadata?: QuantumExportMetadata) {
  return metadata?.name || metadata?.pdbId || metadata?.cid || metadata?.fileName || metadata?.smiles || 'Unnamed molecule';
}

function logText(result: QuantumCalculationResult) {
  return result.outputLog || result.outputTail || 'No engine log was returned.';
}

function formatNumber(value: number) {
  return Number.isFinite(value) ? value.toFixed(4) : 'N/A';
}

function formatSigned(value: number) {
  if (!Number.isFinite(value)) return 'N/A';
  return `${value >= 0 ? '+' : ''}${value.toFixed(4)}`;
}

function worksheetXml(rows: string[][]) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    ${rows.map((row, rowIndex) => xlsxRow(rowIndex + 1, row)).join('\n')}
  </sheetData>
  <sheetProtection sheet="1" objects="1" scenarios="1" formatCells="1" formatColumns="1" formatRows="1" insertColumns="1" insertRows="1" insertHyperlinks="1" deleteColumns="1" deleteRows="1" sort="1" autoFilter="1" pivotTables="1"/>
</worksheet>`;
}

function xlsxRow(rowIndex: number, values: string[]) {
  return `<row r="${rowIndex}">${values.map((value, columnIndex) => xlsxCell(rowIndex, columnIndex, value)).join('')}</row>`;
}

function xlsxCell(rowIndex: number, columnIndex: number, value: string) {
  const ref = `${columnName(columnIndex)}${rowIndex}`;
  return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${escapeXml(value)}</t></is></c>`;
}

function columnName(index: number) {
  let value = '';
  let current = index + 1;
  while (current > 0) {
    const remainder = (current - 1) % 26;
    value = String.fromCharCode(65 + remainder) + value;
    current = Math.floor((current - 1) / 26);
  }
  return value;
}

function docParagraph(value: string, bold = false) {
  const run = `<w:r>${bold ? '<w:rPr><w:b/></w:rPr>' : ''}<w:t xml:space="preserve">${escapeXml(value)}</w:t></w:r>`;
  return `<w:p>${run}</w:p>`;
}

function docTable(rows: string[][]) {
  return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="CBD5E1"/><w:left w:val="single" w:sz="4" w:color="CBD5E1"/><w:bottom w:val="single" w:sz="4" w:color="CBD5E1"/><w:right w:val="single" w:sz="4" w:color="CBD5E1"/><w:insideH w:val="single" w:sz="4" w:color="E2E8F0"/><w:insideV w:val="single" w:sz="4" w:color="E2E8F0"/></w:tblBorders></w:tblPr>${rows
    .map((row) => `<w:tr>${row.map((cell) => `<w:tc><w:p><w:r><w:t xml:space="preserve">${escapeXml(cell)}</w:t></w:r></w:p></w:tc>`).join('')}</w:tr>`)
    .join('')}</w:tbl>`;
}

function xlsxContentTypes() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/>
</Types>`;
}

function docxContentTypes() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/>
</Types>`;
}

function packageRelationships(kind: 'xlsx' | 'docx') {
  const target = kind === 'xlsx' ? 'xl/workbook.xml' : 'word/document.xml';
  const type = kind === 'xlsx'
    ? 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'
    : 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument';
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="${type}" Target="${target}"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
  <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties" Target="docProps/custom.xml"/>
</Relationships>`;
}

function workbookRelationships() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>
</Relationships>`;
}

function coreProperties(generatedAt: Date) {
  const stamp = generatedAt.toISOString();
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>${escapeXml(CHEMVAULT_TITLE)}</dc:title>
  <dc:subject>${escapeXml(CHEMVAULT_SUBJECT)}</dc:subject>
  <dc:creator>${escapeXml(CHEMVAULT_AUTHOR)}</dc:creator>
  <dc:rights>${escapeXml(CHEMVAULT_COPYRIGHT_NOTICE)}</dc:rights>
  <cp:keywords>${escapeXml(CHEMVAULT_KEYWORDS)}</cp:keywords>
  <dc:description>${escapeXml(CHEMVAULT_SUBJECT)}</dc:description>
  <cp:lastModifiedBy>${escapeXml(CHEMVAULT_CREATOR)}</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">${stamp}</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">${stamp}</dcterms:modified>
</cp:coreProperties>`;
}

function appProperties(application: string) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>${escapeXml(application)}</Application>
  <Company>${escapeXml(CHEMVAULT_COMPANY)}</Company>
  <Manager>${escapeXml(CHEMVAULT_CREATOR)}</Manager>
</Properties>`;
}

function customProperties() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="Copyright"><vt:lpwstr>${escapeXml(CHEMVAULT_COPYRIGHT_NOTICE)}</vt:lpwstr></property>
  <property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="3" name="GeneratedBy"><vt:lpwstr>${escapeXml(CHEMVAULT_CREATOR)}</vt:lpwstr></property>
  <property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="4" name="ChemVaultCopyrightLocked"><vt:bool>true</vt:bool></property>
</Properties>`;
}

function wordSettings() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:documentProtection w:edit="readOnly" w:enforcement="1"/>
</w:settings>`;
}

function wordStyles() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style>
</w:styles>`;
}

function createZip(entries: ZipEntry[]) {
  const localParts: Uint8Array[] = [];
  const centralParts: Uint8Array[] = [];
  let offset = 0;

  entries.forEach((entry) => {
    const nameBytes = TEXT_ENCODER.encode(entry.path);
    const data = typeof entry.content === 'string' ? TEXT_ENCODER.encode(entry.content) : entry.content;
    const crc = crc32(data);
    const { date, time } = dosDateTime(new Date());
    const localHeader = new Uint8Array(30 + nameBytes.length);
    const localView = new DataView(localHeader.buffer);
    localView.setUint32(0, 0x04034b50, true);
    localView.setUint16(4, 20, true);
    localView.setUint16(6, 0x0800, true);
    localView.setUint16(8, 0, true);
    localView.setUint16(10, time, true);
    localView.setUint16(12, date, true);
    localView.setUint32(14, crc, true);
    localView.setUint32(18, data.length, true);
    localView.setUint32(22, data.length, true);
    localView.setUint16(26, nameBytes.length, true);
    localHeader.set(nameBytes, 30);
    localParts.push(localHeader, data);

    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const centralView = new DataView(centralHeader.buffer);
    centralView.setUint32(0, 0x02014b50, true);
    centralView.setUint16(4, 20, true);
    centralView.setUint16(6, 20, true);
    centralView.setUint16(8, 0x0800, true);
    centralView.setUint16(10, 0, true);
    centralView.setUint16(12, time, true);
    centralView.setUint16(14, date, true);
    centralView.setUint32(16, crc, true);
    centralView.setUint32(20, data.length, true);
    centralView.setUint32(24, data.length, true);
    centralView.setUint16(28, nameBytes.length, true);
    centralView.setUint32(42, offset, true);
    centralHeader.set(nameBytes, 46);
    centralParts.push(centralHeader);

    offset += localHeader.length + data.length;
  });

  const centralDirectory = concatBytes(centralParts);
  const end = new Uint8Array(22);
  const endView = new DataView(end.buffer);
  endView.setUint32(0, 0x06054b50, true);
  endView.setUint16(8, entries.length, true);
  endView.setUint16(10, entries.length, true);
  endView.setUint32(12, centralDirectory.length, true);
  endView.setUint32(16, offset, true);

  return concatBytes([...localParts, centralDirectory, end]);
}

function concatBytes(parts: Uint8Array[]) {
  const totalLength = parts.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(totalLength);
  let offset = 0;
  parts.forEach((part) => {
    output.set(part, offset);
    offset += part.length;
  });
  return output;
}

function dosDateTime(dateValue: Date) {
  const year = Math.max(1980, dateValue.getFullYear());
  const date = ((year - 1980) << 9) | ((dateValue.getMonth() + 1) << 5) | dateValue.getDate();
  const time = (dateValue.getHours() << 11) | (dateValue.getMinutes() << 5) | Math.floor(dateValue.getSeconds() / 2);
  return { date, time };
}

const CRC_TABLE = Array.from({ length: 256 }, (_, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) {
    value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  }
  return value >>> 0;
});

function crc32(data: Uint8Array) {
  let crc = 0xffffffff;
  data.forEach((byte) => {
    crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  });
  return (crc ^ 0xffffffff) >>> 0;
}

function buildPdf(objects: string[], infoObjectId: number) {
  const parts: string[] = ['%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n'];
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(byteLength(parts.join('')));
    parts.push(`${index + 1} 0 obj\n${object}\nendobj\n`);
  });
  const xrefOffset = byteLength(parts.join(''));
  parts.push(`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`);
  offsets.slice(1).forEach((offset) => {
    parts.push(`${String(offset).padStart(10, '0')} 00000 n \n`);
  });
  parts.push(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info ${infoObjectId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`);
  return TEXT_ENCODER.encode(parts.join(''));
}

function wrapPdfLine(value: string) {
  const text = sanitizePdfText(value);
  const max = 92;
  if (text.length <= max) return [text];
  const lines = [];
  for (let index = 0; index < text.length; index += max) {
    lines.push(text.slice(index, index + max));
  }
  return lines;
}

function pdfDate(value: Date) {
  const pad = (number: number) => String(number).padStart(2, '0');
  return `D:${value.getUTCFullYear()}${pad(value.getUTCMonth() + 1)}${pad(value.getUTCDate())}${pad(value.getUTCHours())}${pad(value.getUTCMinutes())}${pad(value.getUTCSeconds())}Z`;
}

function byteLength(value: string) {
  return TEXT_ENCODER.encode(value).length;
}

function escapeXml(value: string | number) {
  return sanitizeXmlText(String(value))
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function sanitizeXmlText(value: string) {
  return value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/gu, '');
}

function sanitizePdfText(value: string) {
  return value.replace(/[^\x09\x0a\x0d\x20-\x7e]/gu, '?');
}

function escapePdf(value: string) {
  return sanitizePdfText(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}
