import type { QuantumCalculationResult } from '@/lib/chem/quantumTypes';
import type { QuantumResultDiagnosis, QuantumWorkflowIssue } from '@/lib/chem/quantumWorkflow';

export type QuantumExportMetadata = {
  name?: string;
  smiles?: string | null;
  formula?: string | null;
  cid?: string | null;
  pdbId?: string | null;
  fileName?: string | null;
};

export type QuantumExportDocumentContext = {
  brandLogoPng?: Uint8Array;
  charge: number;
  diagnosis?: QuantumResultDiagnosis | null;
  includeLog?: boolean;
  metadata?: QuantumExportMetadata;
  preflightIssues?: QuantumWorkflowIssue[];
  unpairedElectrons: number;
};

const TEXT_ENCODER = new TextEncoder();
const CHEMVAULT_TITLE = 'ChemVault Quantum Calculation Report';
const CHEMVAULT_AUTHOR = 'ChemVault';
const CHEMVAULT_COMPANY = 'ChemVault';
const CHEMVAULT_CREATOR = 'ChemVault Model';
const CHEMVAULT_SUBJECT = 'Quantum calculation results generated by ChemVault Model';
const CHEMVAULT_KEYWORDS = 'ChemVault, quantum calculation, molecule, molecular model';
export const CHEMVAULT_COPYRIGHT_NOTICE = 'Copyright (c) ChemVault. All rights reserved.';
const XLSX_MAX_CELL_TEXT_LENGTH = 32767;
const XLSX_MAX_LOG_ROWS = 50000;
const PDF_PAGE_WIDTH = 612;
const PDF_PAGE_HEIGHT = 792;
const PDF_MARGIN = 42;
const PDF_BOTTOM_MARGIN = 58;
const PDF_CONTENT_WIDTH = PDF_PAGE_WIDTH - PDF_MARGIN * 2;
const PDF_MAX_LOG_LINES = 1600;

export type ZipEntry = {
  path: string;
  content: string | Uint8Array;
};

export function createQuantumExcelWorkbook(result: QuantumCalculationResult, context: QuantumExportDocumentContext) {
  const generatedAt = new Date();
  const includeLog = Boolean(context.includeLog);
  const hasBrandLogo = Boolean(context.brandLogoPng?.length);
  const summaryRows = quantumSummaryRows(result, context, generatedAt);
  const warnings = result.warnings.length ? result.warnings : ['No warnings returned.'];
  const chargeRows = result.charges.map((atom) => [String(atom.index), atom.element, `${formatSigned(atom.charge)} e`]);
  const reviewRows = reviewRowsForExport(context);
  const preflightRows = preflightRowsForExport(context);

  const workbook = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <workbookPr/>
  <sheets>
    <sheet name="Summary" sheetId="1" r:id="rId1"/>
    ${includeLog ? '<sheet name="Engine Log" sheetId="2" r:id="rId2"/>' : ''}
  </sheets>
</workbook>`;

  const summarySheetRows = [
    ['ChemVault Quantum Calculation Report'],
    ...summaryRows,
    [],
    ['Computed Properties'],
    ...computedPropertyRows(result),
    [],
    ['Warnings'],
    ...warnings.map((warning) => [warning]),
    [],
    ['ChemVault Review'],
    ...reviewRows,
    [],
    ['Preflight Checks'],
    ...preflightRows,
    [],
    ['Partial Charges'],
    ['Atom', 'Element', result.chargeModel],
    ...(chargeRows.length ? chargeRows : [['N/A', 'N/A', 'No partial charges returned']]),
    [],
    ['Copyright', CHEMVAULT_COPYRIGHT_NOTICE]
  ];

  const entries: ZipEntry[] = [
    { path: '[Content_Types].xml', content: xlsxContentTypes(includeLog, hasBrandLogo) },
    { path: '_rels/.rels', content: packageRelationships('xlsx') },
    { path: 'docProps/core.xml', content: coreProperties(generatedAt) },
    { path: 'docProps/app.xml', content: appProperties('Microsoft Excel') },
    { path: 'docProps/custom.xml', content: customProperties() },
    { path: 'xl/workbook.xml', content: workbook },
    { path: 'xl/_rels/workbook.xml.rels', content: workbookRelationships(includeLog) },
    { path: 'xl/worksheets/sheet1.xml', content: worksheetXml(summarySheetRows, hasBrandLogo) },
  ];

  if (hasBrandLogo && context.brandLogoPng) {
    entries.push(
      { path: 'xl/worksheets/_rels/sheet1.xml.rels', content: worksheetRelationships() },
      { path: 'xl/drawings/drawing1.xml', content: spreadsheetLogoDrawing() },
      { path: 'xl/drawings/_rels/drawing1.xml.rels', content: spreadsheetLogoRelationships() },
      { path: 'xl/media/chemvault-logo.png', content: context.brandLogoPng }
    );
  }

  if (includeLog) {
    const logLines = boundedLogLines(logText(result));
    const logSheetRows = [
      ['ChemVault Quantum Calculation Engine Log'],
      ['Generated', generatedAt.toISOString()],
      ['Copyright', CHEMVAULT_COPYRIGHT_NOTICE],
      [],
      ...logLines.map((line) => [line])
    ];
    entries.push({ path: 'xl/worksheets/sheet2.xml', content: worksheetXml(logSheetRows) });
  }

  return createZip(entries);
}

export function createQuantumWordDocument(result: QuantumCalculationResult, context: QuantumExportDocumentContext) {
  const generatedAt = new Date();
  const includeLog = Boolean(context.includeLog);
  const hasBrandLogo = Boolean(context.brandLogoPng?.length);
  const warnings = result.warnings.length ? result.warnings : ['No warnings returned.'];
  const body = [
    docParagraph(CHEMVAULT_TITLE, true),
    docParagraph(`Generated: ${generatedAt.toLocaleString()}`),
    docParagraph(`Molecule: ${moleculeLabel(context.metadata)}`),
    docParagraph('Calculation Summary', true),
    docTable(quantumSummaryRows(result, context, generatedAt)),
    docParagraph('Computed Properties', true),
    docTable(computedPropertyRows(result)),
    docParagraph('Partial Charges', true),
    docTable([
      ['Atom', 'Element', result.chargeModel],
      ...(result.charges.length
        ? result.charges.map((atom) => [String(atom.index), atom.element, `${formatSigned(atom.charge)} e`])
        : [['N/A', 'N/A', 'No partial charges returned']])
    ]),
    docParagraph('Warnings', true),
    ...warnings.map((warning) => docParagraph(warning)),
    docParagraph('ChemVault Review', true),
    docTable(reviewRowsForExport(context)),
    docParagraph('Preflight Checks', true),
    docTable(preflightRowsForExport(context)),
    ...(includeLog
      ? [
          docParagraph('Engine Log', true),
          ...logText(result).split(/\r?\n/u).map((line) => docParagraph(line || ' '))
        ]
      : []),
    '<w:sectPr><w:footerReference w:type="default" r:id="rIdFooter1"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:footer="720"/></w:sectPr>'
  ].join('');

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>${body}</w:body>
</w:document>`;

  const entries: ZipEntry[] = [
    { path: '[Content_Types].xml', content: docxContentTypes(hasBrandLogo) },
    { path: '_rels/.rels', content: packageRelationships('docx') },
    { path: 'docProps/core.xml', content: coreProperties(generatedAt) },
    { path: 'docProps/app.xml', content: appProperties('Microsoft Word') },
    { path: 'docProps/custom.xml', content: customProperties() },
    { path: 'word/document.xml', content: documentXml },
    { path: 'word/_rels/document.xml.rels', content: documentRelationships() },
    { path: 'word/footer1.xml', content: wordFooter(hasBrandLogo) },
    { path: 'word/settings.xml', content: wordSettings() },
    { path: 'word/styles.xml', content: wordStyles() }
  ];

  if (hasBrandLogo && context.brandLogoPng) {
    entries.push(
      { path: 'word/_rels/footer1.xml.rels', content: wordFooterRelationships() },
      { path: 'word/media/chemvault-logo.png', content: context.brandLogoPng }
    );
  }

  return createZip(entries);
}

export function createQuantumPdfDocument(result: QuantumCalculationResult, context: QuantumExportDocumentContext) {
  const generatedAt = new Date();
  const includeLog = Boolean(context.includeLog);
  const brandLogo = context.brandLogoPng ? parsePdfPng(context.brandLogoPng) : null;
  const layout = createPdfLayout();
  drawPdfHero(layout, result, context, generatedAt);
  drawPdfMetricGrid(layout, [
    ['Total energy', result.energyHartree === null ? 'N/A' : `${formatNumber(result.energyHartree)} Eh`],
    ['Dipole magnitude', result.dipoleDebye ? `${formatNumber(result.dipoleDebye.total)} D` : 'N/A'],
    ['Partial charges', String(result.charges.length)],
    ['Run mode', result.gaussianTaskLabel || (result.calculationMode === 'geometry-optimization' ? 'Optimized' : 'Single point')],
    ['Engine time', formatElapsedMs(result.engineElapsedMs ?? result.elapsedMs)],
    ['ChemVault processing', formatElapsedMs(result.postProcessingElapsedMs ?? Math.max(0, result.elapsedMs - (result.engineElapsedMs ?? result.elapsedMs)))],
    ['Total elapsed', formatElapsedMs(result.elapsedMs)]
  ]);
  if (result.dipoleDebye) drawPdfDipoleCard(layout, result);
  drawPdfAdvancedResults(layout, result);
  drawPdfChargeTable(layout, result);
  if (result.warnings.length > 0) drawPdfWarnings(layout, result.warnings);
  drawPdfReview(layout, context);
  if (includeLog) drawPdfEngineLog(layout, result);
  const pageContents = finishPdfLayout(layout, Boolean(brandLogo));

  const objects: PdfObject[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'
  ];

  let logoObjectId: number | null = null;
  if (brandLogo) {
    logoObjectId = objects.length + 1;
    objects.push(pdfPngImageObject(brandLogo));
  }

  const pageRefs: string[] = [];
  pageContents.forEach((content) => {
    const pageObjectId = objects.length + 1;
    const contentObjectId = pageObjectId + 1;
    pageRefs.push(`${pageObjectId} 0 R`);
    const logoResource = logoObjectId ? ` /XObject << /ImLogo ${logoObjectId} 0 R >>` : '';
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PDF_PAGE_WIDTH} ${PDF_PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R >>${logoResource} >> /Contents ${contentObjectId} 0 R >>`);
    objects.push(`<< /Length ${byteLength(content)} >>\nstream\n${content}\nendstream`);
  });

  objects[1] = `<< /Type /Pages /Kids [${pageRefs.join(' ')}] /Count ${pageContents.length} >>`;
  const infoObjectId = objects.length + 1;
  objects.push(`<< /Title (${escapePdf(CHEMVAULT_TITLE)}) /Author (${escapePdf(CHEMVAULT_AUTHOR)}) /Subject (${escapePdf(CHEMVAULT_SUBJECT)}) /Keywords (${escapePdf(CHEMVAULT_KEYWORDS)}) /Creator (${escapePdf(CHEMVAULT_CREATOR)}) /Producer (${escapePdf(CHEMVAULT_CREATOR)}) /CreationDate (${pdfDate(generatedAt)}) /ModDate (${pdfDate(generatedAt)}) /Copyright (${escapePdf(CHEMVAULT_COPYRIGHT_NOTICE)}) >>`);

  return buildPdf(objects, infoObjectId);
}

type PdfFont = 'F1' | 'F2' | 'F3';

type PdfObject = string | Uint8Array;

type PdfPngImage = {
  compressedData: Uint8Array;
  height: number;
  width: number;
};

type PdfLayout = {
  commands: string[];
  pages: string[];
  pageNumber: number;
  y: number;
};

type PdfTextOptions = {
  color?: string;
  font?: PdfFont;
  lineHeight?: number;
  maxLines?: number;
  size?: number;
};

function createPdfLayout(): PdfLayout {
  const layout: PdfLayout = {
    commands: [],
    pages: [],
    pageNumber: 0,
    y: 0
  };
  startPdfPage(layout);
  return layout;
}

function finishPdfLayout(layout: PdfLayout, hasBrandLogo = false) {
  if (layout.commands.length > 0) layout.pages.push(layout.commands.join('\n'));
  const totalPages = layout.pages.length;
  return layout.pages.map((content, index) => [content, pdfFooterCommands(index + 1, totalPages, hasBrandLogo)].join('\n'));
}

function startPdfPage(layout: PdfLayout) {
  if (layout.commands.length > 0) layout.pages.push(layout.commands.join('\n'));
  layout.pageNumber += 1;
  layout.commands = [];
  layout.y = PDF_PAGE_HEIGHT - 48;
}

function ensurePdfSpace(layout: PdfLayout, height: number) {
  if (layout.y - height < PDF_BOTTOM_MARGIN) startPdfPage(layout);
}

function drawPdfHero(layout: PdfLayout, result: QuantumCalculationResult, context: QuantumExportDocumentContext, generatedAt: Date) {
  const panelHeight = 126;
  ensurePdfSpace(layout, panelHeight + 16);
  const bottom = layout.y - panelHeight;
  drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, panelHeight, {
    fill: '#f0f9ff',
    stroke: '#bae6fd'
  });
  drawPdfText(layout, CHEMVAULT_TITLE, PDF_MARGIN + 18, layout.y - 30, { color: '#0f172a', font: 'F2', size: 21 });
  drawPdfText(layout, `Generated ${generatedAt.toLocaleString()}`, PDF_MARGIN + 18, layout.y - 52, { color: '#64748b', size: 9.5 });
  drawPdfWrappedText(layout, `Molecule: ${moleculeLabel(context.metadata)}`, PDF_MARGIN + 18, layout.y - 72, 330, { color: '#334155', size: 10.5 });
  drawPdfPill(layout, result.ok ? 'Completed' : 'Needs review', PDF_PAGE_WIDTH - PDF_MARGIN - 100, layout.y - 40, result.ok ? '#ecfdf5' : '#fff7ed', result.ok ? '#047857' : '#9a3412');

  const summaryBottom = bottom + 18;
  drawPdfMiniMetric(layout, PDF_MARGIN + 18, summaryBottom, 112, 'Engine', result.engineLabel);
  drawPdfMiniMetric(layout, PDF_MARGIN + 140, summaryBottom, 126, 'Method', result.method);
  drawPdfMiniMetric(layout, PDF_MARGIN + 276, summaryBottom, 104, 'Charge', String(context.charge));
  drawPdfMiniMetric(layout, PDF_MARGIN + 390, summaryBottom, 102, 'Unpaired', String(context.unpairedElectrons));
  layout.y = bottom - 16;

  const status = result.ok ? 'Ready for export' : result.error || 'Calculation did not complete normally.';
  const statusHeight = Math.max(42, 22 + wrapPdfText(status, PDF_CONTENT_WIDTH - 36, 9.5).length * 12);
  ensurePdfSpace(layout, statusHeight + 12);
  const statusBottom = layout.y - statusHeight;
  drawPdfRect(layout, PDF_MARGIN, statusBottom, PDF_CONTENT_WIDTH, statusHeight, {
    fill: result.ok ? '#f0fdf4' : '#fff7ed',
    stroke: result.ok ? '#bbf7d0' : '#fed7aa'
  });
  drawPdfText(layout, 'Status', PDF_MARGIN + 18, layout.y - 17, { color: result.ok ? '#047857' : '#9a3412', font: 'F2', size: 9 });
  drawPdfWrappedText(layout, status, PDF_MARGIN + 18, layout.y - 32, PDF_CONTENT_WIDTH - 36, { color: '#334155', size: 9.5, lineHeight: 12 });
  layout.y = statusBottom - 16;
}

function drawPdfMetricGrid(layout: PdfLayout, metrics: Array<[string, string]>) {
  drawPdfSectionTitle(layout, 'Computed properties');
  const columns = 3;
  const gap = 10;
  const cardWidth = (PDF_CONTENT_WIDTH - gap * (columns - 1)) / columns;
  const cardHeight = 66;
  metrics.forEach(([label, value], index) => {
    if (index % columns === 0) ensurePdfSpace(layout, cardHeight + 12);
    const column = index % columns;
    const rowTop = layout.y;
    const x = PDF_MARGIN + column * (cardWidth + gap);
    const bottom = rowTop - cardHeight;
    drawPdfRect(layout, x, bottom, cardWidth, cardHeight, { fill: '#f8fafc', stroke: '#e2e8f0' });
    drawPdfText(layout, label, x + 12, rowTop - 18, { color: '#64748b', font: 'F2', size: 8 });
    drawPdfWrappedText(layout, value, x + 12, rowTop - 40, cardWidth - 24, { color: '#020617', font: 'F2', size: 13.5, lineHeight: 14, maxLines: 2 });
    if (column === columns - 1 || index === metrics.length - 1) layout.y = bottom - 10;
  });
  layout.y -= 4;
}

function drawPdfDipoleCard(layout: PdfLayout, result: QuantumCalculationResult) {
  if (!result.dipoleDebye) return;
  const height = 118;
  ensurePdfSpace(layout, height + 14);
  const bottom = layout.y - height;
  drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, height, { fill: '#f8fafc', stroke: '#e2e8f0' });
  drawPdfText(layout, 'Dipole vector', PDF_MARGIN + 16, layout.y - 22, { color: '#020617', font: 'F2', size: 13 });
  drawPdfText(layout, `Debye components returned by ${result.engineLabel}.`, PDF_MARGIN + 16, layout.y - 39, { color: '#64748b', size: 9 });

  const axisWidth = (PDF_CONTENT_WIDTH - 52) / 3;
  const axisBottom = bottom + 18;
  ([
    ['X', result.dipoleDebye.x],
    ['Y', result.dipoleDebye.y],
    ['Z', result.dipoleDebye.z]
  ] as Array<[string, number]>).forEach(([axis, value], index) => {
    const x = PDF_MARGIN + 16 + index * (axisWidth + 10);
    drawPdfRect(layout, x, axisBottom, axisWidth, 42, { fill: '#ffffff' });
    drawPdfText(layout, axis, x + 10, axisBottom + 26, { color: '#94a3b8', font: 'F2', size: 8 });
    drawPdfText(layout, `${formatSigned(value)} D`, x + 10, axisBottom + 11, { color: '#0f172a', font: 'F3', size: 10.5 });
  });
  layout.y = bottom - 16;
}

function drawPdfAdvancedResults(layout: PdfLayout, result: QuantumCalculationResult) {
  const rows: Array<[string, string]> = [];
  if (result.frontierOrbitals) {
    rows.push(
      ['Alpha HOMO', result.frontierOrbitals.alphaHomoEv === null ? 'N/A' : `${formatNumber(result.frontierOrbitals.alphaHomoEv)} eV`],
      ['Alpha LUMO', result.frontierOrbitals.alphaLumoEv === null ? 'N/A' : `${formatNumber(result.frontierOrbitals.alphaLumoEv)} eV`],
      ['HOMO-LUMO gap', result.frontierOrbitals.gapEv === null ? 'N/A' : `${formatNumber(result.frontierOrbitals.gapEv)} eV`]
    );
  }
  if (result.frequencySummary) {
    rows.push(
      ['Imaginary modes', String(result.frequencySummary.imaginaryCount)],
      ['Lowest frequency', result.frequencySummary.lowestFrequencyCm1 === null ? 'N/A' : `${formatNumber(result.frequencySummary.lowestFrequencyCm1)} cm-1`],
      ['Parsed modes', String(result.frequencySummary.modes.length)]
    );
  }
  if (result.thermochemistry) {
    rows.push(
      ['ZPE correction', result.thermochemistry.zeroPointCorrectionHartree === null ? 'N/A' : `${formatNumber(result.thermochemistry.zeroPointCorrectionHartree)} Eh`],
      ['Thermal Gibbs', result.thermochemistry.thermalCorrectionToGibbsHartree === null ? 'N/A' : `${formatNumber(result.thermochemistry.thermalCorrectionToGibbsHartree)} Eh`]
    );
  }
  if (result.excitedStates?.length) {
    rows.push(
      ['Excited states parsed', String(result.excitedStates.length)],
      ['First excited state', `${formatNumber(result.excitedStates[0].energyEv)} eV / ${formatNumber(result.excitedStates[0].wavelengthNm)} nm`]
    );
  }
  if (result.nmrShielding?.length) {
    rows.push(
      ['NMR shieldings parsed', String(result.nmrShielding.length)],
      ['First isotropic shielding', `${result.nmrShielding[0].element}${result.nmrShielding[0].index}: ${formatNumber(result.nmrShielding[0].isotropicPpm)} ppm`]
    );
  }
  if (!rows.length) return;

  drawPdfSectionTitle(layout, 'Advanced parsed results');
  const columns = 2;
  const gap = 10;
  const cardWidth = (PDF_CONTENT_WIDTH - gap) / columns;
  const cardHeight = 50;
  rows.forEach(([label, value], index) => {
    if (index % columns === 0) ensurePdfSpace(layout, cardHeight + 12);
    const column = index % columns;
    const x = PDF_MARGIN + column * (cardWidth + gap);
    const bottom = layout.y - cardHeight;
    drawPdfRect(layout, x, bottom, cardWidth, cardHeight, { fill: '#f8fafc', stroke: '#e2e8f0' });
    drawPdfText(layout, label, x + 12, layout.y - 16, { color: '#64748b', font: 'F2', size: 8 });
    drawPdfWrappedText(layout, value, x + 12, layout.y - 34, cardWidth - 24, { color: '#020617', font: 'F2', size: 11, lineHeight: 11, maxLines: 1 });
    if (column === columns - 1 || index === rows.length - 1) layout.y = bottom - 10;
  });
  layout.y -= 4;
}

function drawPdfChargeTable(layout: PdfLayout, result: QuantumCalculationResult) {
  drawPdfSectionTitle(layout, 'Partial charges');
  const header = ['Atom', 'Elem', result.chargeModel];
  const rows = result.charges.length
    ? result.charges.map((atom) => [String(atom.index), atom.element, `${formatSigned(atom.charge)} e`, atom.charge >= 0 ? '#be123c' : '#075985'])
    : [['N/A', 'N/A', 'No partial charges returned.', '#334155']];
  const widths = [72, 74, PDF_CONTENT_WIDTH - 146];
  let headerDrawn = false;

  rows.forEach((row) => {
    if (!headerDrawn || layout.y - 29 < PDF_BOTTOM_MARGIN) {
      ensurePdfSpace(layout, 60);
      drawPdfTableHeader(layout, header, widths);
      headerDrawn = true;
    }
    const bottom = layout.y - 28;
    drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, 28, { fill: '#ffffff', stroke: '#e2e8f0' });
    drawPdfText(layout, row[0], PDF_MARGIN + 12, layout.y - 18, { color: '#334155', font: 'F3', size: 9 });
    drawPdfText(layout, row[1], PDF_MARGIN + widths[0] + 12, layout.y - 18, { color: '#020617', font: 'F2', size: 10 });
    drawPdfText(layout, row[2], PDF_MARGIN + widths[0] + widths[1] + 12, layout.y - 18, { color: row[3], font: 'F3', size: 9 });
    layout.y = bottom;
  });
  layout.y -= 16;
}

function drawPdfWarnings(layout: PdfLayout, warnings: string[]) {
  drawPdfSectionTitle(layout, 'Warnings');
  warnings.forEach((warning) => {
    const lines = wrapPdfText(warning, PDF_CONTENT_WIDTH - 32, 9.5);
    const height = 22 + lines.length * 12;
    ensurePdfSpace(layout, height + 10);
    const bottom = layout.y - height;
    drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, height, { fill: '#fffbeb', stroke: '#fde68a' });
    lines.forEach((line, index) => {
      drawPdfText(layout, line, PDF_MARGIN + 16, layout.y - 18 - index * 12, { color: '#92400e', size: 9.5 });
    });
    layout.y = bottom - 8;
  });
  layout.y -= 6;
}

function drawPdfReview(layout: PdfLayout, context: QuantumExportDocumentContext) {
  const diagnosis = context.diagnosis;
  const preflightIssues = context.preflightIssues || [];
  if (!diagnosis && preflightIssues.length === 0) return;

  drawPdfSectionTitle(layout, 'ChemVault review');
  if (diagnosis) {
    const lines = [
      `${diagnosis.title}: ${diagnosis.summary}`,
      ...diagnosis.suggestedActions.map((action) => `Action: ${action}`)
    ];
    lines.forEach((line) => {
      const wrapped = wrapPdfText(line, PDF_CONTENT_WIDTH - 32, 9.5);
      const height = 18 + wrapped.length * 12;
      ensurePdfSpace(layout, height + 8);
      const bottom = layout.y - height;
      const tone = diagnosis.severity === 'success'
        ? { fill: '#f0fdf4', stroke: '#bbf7d0', color: '#047857' }
        : diagnosis.severity === 'error'
          ? { fill: '#fff1f2', stroke: '#fecdd3', color: '#be123c' }
          : { fill: '#fff7ed', stroke: '#fed7aa', color: '#9a3412' };
      drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, height, { fill: tone.fill, stroke: tone.stroke });
      wrapped.forEach((wrappedLine, index) => {
        drawPdfText(layout, wrappedLine, PDF_MARGIN + 16, layout.y - 17 - index * 12, { color: tone.color, size: 9.5 });
      });
      layout.y = bottom - 8;
    });
  }

  preflightIssues.slice(0, 8).forEach((issue) => {
    const text = `${issue.severity.toUpperCase()}: ${issue.title}. ${issue.detail}${issue.action ? ` Action: ${issue.action}` : ''}`;
    const lines = wrapPdfText(text, PDF_CONTENT_WIDTH - 32, 8.8);
    const height = 18 + lines.length * 11;
    ensurePdfSpace(layout, height + 6);
    const bottom = layout.y - height;
    drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, height, { fill: '#f8fafc', stroke: '#e2e8f0' });
    lines.forEach((line, index) => {
      drawPdfText(layout, line, PDF_MARGIN + 16, layout.y - 16 - index * 11, { color: '#334155', size: 8.8 });
    });
    layout.y = bottom - 6;
  });
}

function drawPdfEngineLog(layout: PdfLayout, result: QuantumCalculationResult) {
  drawPdfSectionTitle(layout, 'Calculation log');
  const logLines = boundedPdfLogLines(logText(result))
    .flatMap((line) => wrapPdfPreText(line || ' ', PDF_CONTENT_WIDTH - 32, 7.5));
  let index = 0;

  while (index < logLines.length) {
    if (layout.y - 80 < PDF_BOTTOM_MARGIN) startPdfPage(layout);
    const availableHeight = Math.max(60, layout.y - PDF_BOTTOM_MARGIN - 12);
    const availableLines = Math.max(1, Math.min(logLines.length - index, Math.floor((availableHeight - 24) / 9.5)));
    const blockHeight = availableLines * 9.5 + 24;
    const bottom = layout.y - blockHeight;
    drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, blockHeight, { fill: '#020617', stroke: '#020617' });
    for (let lineIndex = 0; lineIndex < availableLines; lineIndex += 1) {
      drawPdfText(layout, logLines[index + lineIndex], PDF_MARGIN + 16, layout.y - 18 - lineIndex * 9.5, {
        color: '#e2e8f0',
        font: 'F3',
        size: 7.5
      });
    }
    index += availableLines;
    layout.y = bottom - 12;
  }
}

function drawPdfSectionTitle(layout: PdfLayout, title: string) {
  ensurePdfSpace(layout, 28);
  drawPdfText(layout, title, PDF_MARGIN, layout.y - 4, { color: '#020617', font: 'F2', size: 14 });
  layout.y -= 24;
}

function drawPdfTableHeader(layout: PdfLayout, cells: string[], widths: number[]) {
  const height = 28;
  const bottom = layout.y - height;
  drawPdfRect(layout, PDF_MARGIN, bottom, PDF_CONTENT_WIDTH, height, { fill: '#f1f5f9', stroke: '#e2e8f0' });
  let x = PDF_MARGIN + 12;
  cells.forEach((cell, index) => {
    drawPdfWrappedText(layout, cell, x, layout.y - 18, widths[index] - 18, { color: '#64748b', font: 'F2', size: 8, lineHeight: 8, maxLines: 1 });
    x += widths[index];
  });
  layout.y = bottom;
}

function drawPdfMiniMetric(layout: PdfLayout, x: number, bottom: number, width: number, label: string, value: string) {
  drawPdfRect(layout, x, bottom, width, 43, { fill: '#ffffff', stroke: '#dbeafe' });
  drawPdfText(layout, label, x + 9, bottom + 27, { color: '#64748b', font: 'F2', size: 7.5 });
  drawPdfWrappedText(layout, value, x + 9, bottom + 13, width - 18, { color: '#020617', font: 'F2', size: 9, lineHeight: 9, maxLines: 1 });
}

function drawPdfPill(layout: PdfLayout, label: string, x: number, y: number, fill: string, color: string) {
  drawPdfRect(layout, x, y - 20, 88, 24, { fill, stroke: fill });
  drawPdfText(layout, label, x + 11, y - 11, { color, font: 'F2', size: 8.5 });
}

function pdfFooterCommands(pageNumber: number, totalPages: number, hasBrandLogo = false) {
  const footerLayout: PdfLayout = {
    commands: [],
    pages: [],
    pageNumber,
    y: 0
  };
  drawPdfLine(footerLayout, PDF_MARGIN, 42, PDF_PAGE_WIDTH - PDF_MARGIN, 42, '#cbd5e1');
  if (hasBrandLogo) {
    footerLayout.commands.push(`q\n18 0 0 18 ${PDF_MARGIN} 15 cm\n/ImLogo Do\nQ`);
  }
  drawPdfText(footerLayout, CHEMVAULT_COPYRIGHT_NOTICE, PDF_MARGIN + (hasBrandLogo ? 24 : 0), 26, { color: '#64748b', size: 7.5 });
  drawPdfText(footerLayout, `Page ${pageNumber} of ${totalPages}`, PDF_PAGE_WIDTH - PDF_MARGIN - 62, 26, { color: '#64748b', size: 7.5 });
  return footerLayout.commands.join('\n');
}

function drawPdfRect(layout: PdfLayout, x: number, y: number, width: number, height: number, options: { fill?: string; lineWidth?: number; stroke?: string } = {}) {
  const fill = options.fill ? `${pdfColor(options.fill)} rg` : '';
  const stroke = options.stroke ? `${pdfColor(options.stroke)} RG` : '';
  const lineWidth = `${options.lineWidth ?? 1} w`;
  const operation = options.fill && options.stroke ? 'B' : options.fill ? 'f' : 'S';
  layout.commands.push(['q', fill, stroke, lineWidth, `${pdfNumber(x)} ${pdfNumber(y)} ${pdfNumber(width)} ${pdfNumber(height)} re ${operation}`, 'Q'].filter(Boolean).join('\n'));
}

function drawPdfLine(layout: PdfLayout, x1: number, y1: number, x2: number, y2: number, color: string) {
  layout.commands.push(`q\n${pdfColor(color)} RG\n0.75 w\n${pdfNumber(x1)} ${pdfNumber(y1)} m\n${pdfNumber(x2)} ${pdfNumber(y2)} l\nS\nQ`);
}

function drawPdfText(layout: PdfLayout, value: string, x: number, y: number, options: PdfTextOptions = {}) {
  const font = options.font || 'F1';
  const size = options.size || 10;
  const color = options.color || '#0f172a';
  layout.commands.push(`q\n${pdfColor(color)} rg\nBT\n/${font} ${pdfNumber(size)} Tf\n1 0 0 1 ${pdfNumber(x)} ${pdfNumber(y)} Tm\n(${escapePdf(value)}) Tj\nET\nQ`);
}

function drawPdfWrappedText(layout: PdfLayout, value: string, x: number, y: number, width: number, options: PdfTextOptions = {}) {
  const size = options.size || 10;
  const lineHeight = options.lineHeight || size + 3;
  const lines = wrapPdfText(value, width, size, options.font).slice(0, options.maxLines || Number.POSITIVE_INFINITY);
  lines.forEach((line, index) => {
    drawPdfText(layout, line, x, y - index * lineHeight, options);
  });
  return lines.length * lineHeight;
}

function wrapPdfText(value: string, width: number, size: number, font: PdfFont = 'F1') {
  const text = sanitizePdfText(value).replace(/\s+/gu, ' ').trim();
  if (!text) return [''];
  const lines: string[] = [];
  let line = '';
  text.split(' ').forEach((word) => {
    const candidate = line ? `${line} ${word}` : word;
    if (approxPdfTextWidth(candidate, size, font) <= width) {
      line = candidate;
      return;
    }
    if (line) lines.push(line);
    if (approxPdfTextWidth(word, size, font) <= width) {
      line = word;
      return;
    }
    const maxChars = Math.max(8, Math.floor(width / (size * (font === 'F3' ? 0.6 : 0.52))));
    for (let index = 0; index < word.length; index += maxChars) {
      const chunk = word.slice(index, index + maxChars);
      if (index + maxChars < word.length) lines.push(chunk);
      else line = chunk;
    }
  });
  if (line) lines.push(line);
  return lines;
}

function wrapPdfPreText(value: string, width: number, size: number) {
  const text = sanitizePdfText(value).replace(/\t/gu, '    ');
  const maxChars = Math.max(8, Math.floor(width / (size * 0.6)));
  if (!text) return [' '];
  const lines: string[] = [];
  for (let index = 0; index < text.length; index += maxChars) {
    lines.push(text.slice(index, index + maxChars));
  }
  return lines;
}

function approxPdfTextWidth(value: string, size: number, font: PdfFont) {
  const factor = font === 'F3' ? 0.6 : font === 'F2' ? 0.55 : 0.52;
  return sanitizePdfText(value).length * size * factor;
}

function pdfColor(hex: string) {
  const normalized = hex.replace('#', '');
  const red = Number.parseInt(normalized.slice(0, 2), 16) / 255;
  const green = Number.parseInt(normalized.slice(2, 4), 16) / 255;
  const blue = Number.parseInt(normalized.slice(4, 6), 16) / 255;
  return `${pdfNumber(red)} ${pdfNumber(green)} ${pdfNumber(blue)}`;
}

function pdfNumber(value: number) {
  return Number.isInteger(value) ? String(value) : value.toFixed(3).replace(/0+$/u, '').replace(/\.$/u, '');
}

function boundedPdfLogLines(value: string) {
  const lines = value.split(/\r?\n/u);
  if (lines.length <= PDF_MAX_LOG_LINES) return lines;
  return [
    ...lines.slice(0, PDF_MAX_LOG_LINES),
    'Log truncated in PDF export. Use Export Log for the complete engine output.'
  ];
}

function quantumSummaryRows(result: QuantumCalculationResult, context: QuantumExportDocumentContext, generatedAt: Date) {
  return [
    ['Generated', generatedAt.toISOString()],
    ['Molecule', moleculeLabel(context.metadata)],
    ['Engine', result.engineLabel],
    ['Engine version', result.engineVersion || result.runManifest?.engine.version || 'Not reported'],
    ['ChemVault build', result.runManifest ? `${result.runManifest.app.version} (${result.runManifest.app.buildId || 'build not reported'})` : 'Not reported'],
    ['Method', result.method],
    ['Calculation mode', result.gaussianTaskLabel || result.calculationMode],
    ['Performance profile', result.performanceProfile ? profileLabel(result.performanceProfile) : 'N/A'],
    ['Output detail', result.outputDetail || 'standard'],
    ['Processors', result.resourceUsage ? String(result.resourceUsage.processorCount) : 'Engine managed'],
    ['Memory', result.resourceUsage ? `${result.resourceUsage.memoryGb} GB` : 'Engine managed'],
    ['Checkpoint reused', result.reusedCheckpoint ? 'Yes' : 'No'],
    ['Total charge', String(context.charge)],
    ['Unpaired electrons', String(context.unpairedElectrons)],
    ['Result completeness', typeof context.diagnosis?.completenessScore === 'number' ? `${context.diagnosis.completenessScore}/100` : 'N/A'],
    ['Status', result.ok ? 'Completed' : result.error || 'Not completed'],
    ['Structure SHA-256', result.runManifest?.provenance.structureSha256 || 'Not recorded'],
    ['Input SHA-256', result.runManifest?.provenance.inputSha256 || 'Not recorded'],
    ['Output SHA-256', result.runManifest?.provenance.outputSha256 || 'Not recorded']
  ];
}

function computedPropertyRows(result: QuantumCalculationResult) {
  const rows = [
    ['Total energy', result.energyHartree === null ? 'N/A' : `${formatNumber(result.energyHartree)} Eh`],
    ['Dipole magnitude', result.dipoleDebye ? `${formatNumber(result.dipoleDebye.total)} D` : 'N/A'],
    ['Dipole X', result.dipoleDebye ? `${formatSigned(result.dipoleDebye.x)} D` : 'N/A'],
    ['Dipole Y', result.dipoleDebye ? `${formatSigned(result.dipoleDebye.y)} D` : 'N/A'],
    ['Dipole Z', result.dipoleDebye ? `${formatSigned(result.dipoleDebye.z)} D` : 'N/A'],
    ['Partial charges', String(result.charges.length)],
    ['Charge model', result.chargeModel],
    ['Engine time', formatElapsedMs(result.engineElapsedMs ?? result.elapsedMs)],
    ['ChemVault processing time', formatElapsedMs(result.postProcessingElapsedMs ?? Math.max(0, result.elapsedMs - (result.engineElapsedMs ?? result.elapsedMs)))],
    ['Total elapsed time', formatElapsedMs(result.elapsedMs)]
  ];
  if (result.frontierOrbitals) {
    rows.push(
      ['Alpha HOMO', result.frontierOrbitals.alphaHomoEv === null ? 'N/A' : `${formatNumber(result.frontierOrbitals.alphaHomoEv)} eV`],
      ['Alpha LUMO', result.frontierOrbitals.alphaLumoEv === null ? 'N/A' : `${formatNumber(result.frontierOrbitals.alphaLumoEv)} eV`],
      ['HOMO-LUMO gap', result.frontierOrbitals.gapEv === null ? 'N/A' : `${formatNumber(result.frontierOrbitals.gapEv)} eV`]
    );
  }
  if (result.frequencySummary) {
    rows.push(
      ['Imaginary frequencies', String(result.frequencySummary.imaginaryCount)],
      ['Lowest frequency', result.frequencySummary.lowestFrequencyCm1 === null ? 'N/A' : `${formatNumber(result.frequencySummary.lowestFrequencyCm1)} cm-1`]
    );
  }
  if (result.thermochemistry) {
    rows.push(
      ['Zero-point correction', result.thermochemistry.zeroPointCorrectionHartree === null ? 'N/A' : `${formatNumber(result.thermochemistry.zeroPointCorrectionHartree)} Eh`],
      ['Thermal correction to Gibbs', result.thermochemistry.thermalCorrectionToGibbsHartree === null ? 'N/A' : `${formatNumber(result.thermochemistry.thermalCorrectionToGibbsHartree)} Eh`]
    );
  }
  if (result.excitedStates?.length) {
    rows.push(
      ['Excited states parsed', String(result.excitedStates.length)],
      ['First excited state', `${formatNumber(result.excitedStates[0].energyEv)} eV / ${formatNumber(result.excitedStates[0].wavelengthNm)} nm`]
    );
  }
  if (result.nmrShielding?.length) {
    rows.push(
      ['NMR shieldings parsed', String(result.nmrShielding.length)],
      ['First isotropic shielding', `${result.nmrShielding[0].element}${result.nmrShielding[0].index}: ${formatNumber(result.nmrShielding[0].isotropicPpm)} ppm`]
    );
  }
  return rows;
}

function reviewRowsForExport(context: QuantumExportDocumentContext) {
  const diagnosis = context.diagnosis;
  if (!diagnosis) return [['Status', 'No ChemVault diagnosis was generated.']];
  return [
    ['Status', diagnosis.title],
    ['Severity', diagnosis.severity],
    ['Result completeness', typeof diagnosis.completenessScore === 'number' ? `${diagnosis.completenessScore}/100` : 'N/A'],
    ['Summary', diagnosis.summary],
    ['Completeness factors', diagnosis.completenessFactors?.length ? diagnosis.completenessFactors.join(' | ') : 'N/A'],
    ['Recommended actions', diagnosis.suggestedActions.length ? diagnosis.suggestedActions.join(' | ') : 'No additional action suggested.']
  ];
}

function preflightRowsForExport(context: QuantumExportDocumentContext) {
  const issues = context.preflightIssues || [];
  if (!issues.length) return [['Status', 'No preflight issues found.']];
  return issues.map((issue) => [
    issue.severity,
    issue.title,
    issue.detail,
    issue.action || ''
  ]);
}

function moleculeLabel(metadata?: QuantumExportMetadata) {
  return metadata?.name || metadata?.pdbId || metadata?.cid || metadata?.fileName || metadata?.smiles || 'Unnamed molecule';
}

function formatElapsedMs(value: number) {
  return `${(Math.max(0, value) / 1000).toFixed(1)} s`;
}

function profileLabel(value: string) {
  if (value === 'fast-screening') return 'Fast screening';
  if (value === 'high-accuracy') return 'Advanced DFT';
  if (value === 'balanced') return 'Balanced';
  return value;
}

function logText(result: QuantumCalculationResult) {
  return result.outputLog || result.outputTail || 'No engine log was returned.';
}

function formatNumber(value: number) {
  return Number.isFinite(value) ? value.toFixed(4) : 'N/A';
}

function formatSigned(value: number) {
  if (!Number.isFinite(value)) return 'N/A';
  return `${value >= 0 ? '+' : ''}${value.toFixed(4)}`;
}

function worksheetXml(rows: string[][], hasBrandLogo = false) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheetData>
    ${rows.map((row, rowIndex) => xlsxRow(rowIndex + 1, row)).join('\n')}
  </sheetData>
  ${hasBrandLogo ? '<drawing r:id="rIdLogo"/>' : ''}
</worksheet>`;
}

function xlsxRow(rowIndex: number, values: string[]) {
  return `<row r="${rowIndex}">${values.map((value, columnIndex) => xlsxCell(rowIndex, columnIndex, value)).join('')}</row>`;
}

function xlsxCell(rowIndex: number, columnIndex: number, value: string) {
  const ref = `${columnName(columnIndex)}${rowIndex}`;
  return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${escapeXml(xlsxCellText(value))}</t></is></c>`;
}

function columnName(index: number) {
  let value = '';
  let current = index + 1;
  while (current > 0) {
    const remainder = (current - 1) % 26;
    value = String.fromCharCode(65 + remainder) + value;
    current = Math.floor((current - 1) / 26);
  }
  return value;
}

function docParagraph(value: string, bold = false) {
  const run = `<w:r>${bold ? '<w:rPr><w:b/></w:rPr>' : ''}<w:t xml:space="preserve">${escapeXml(value)}</w:t></w:r>`;
  return `<w:p>${run}</w:p>`;
}

function docTable(rows: string[][]) {
  return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="CBD5E1"/><w:left w:val="single" w:sz="4" w:color="CBD5E1"/><w:bottom w:val="single" w:sz="4" w:color="CBD5E1"/><w:right w:val="single" w:sz="4" w:color="CBD5E1"/><w:insideH w:val="single" w:sz="4" w:color="E2E8F0"/><w:insideV w:val="single" w:sz="4" w:color="E2E8F0"/></w:tblBorders></w:tblPr>${rows
    .map((row) => `<w:tr>${row.map((cell) => `<w:tc><w:p><w:r><w:t xml:space="preserve">${escapeXml(cell)}</w:t></w:r></w:p></w:tc>`).join('')}</w:tr>`)
    .join('')}</w:tbl>`;
}

function xlsxContentTypes(includeLog = true, hasBrandLogo = false) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  ${hasBrandLogo ? '<Default Extension="png" ContentType="image/png"/>' : ''}
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  ${includeLog ? '<Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>' : ''}
  ${hasBrandLogo ? '<Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>' : ''}
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/>
</Types>`;
}

function docxContentTypes(hasBrandLogo = false) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  ${hasBrandLogo ? '<Default Extension="png" ContentType="image/png"/>' : ''}
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>
  <Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/>
</Types>`;
}

function packageRelationships(kind: 'xlsx' | 'docx') {
  const target = kind === 'xlsx' ? 'xl/workbook.xml' : 'word/document.xml';
  const type = kind === 'xlsx'
    ? 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'
    : 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument';
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="${type}" Target="${target}"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
  <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties" Target="docProps/custom.xml"/>
</Relationships>`;
}

function documentRelationships() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rIdFooter1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>
</Relationships>`;
}

function wordFooterRelationships() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rIdLogo" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/chemvault-logo.png"/>
</Relationships>`;
}

function workbookRelationships(includeLog = true) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
  ${includeLog ? '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>' : ''}
</Relationships>`;
}

function worksheetRelationships() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rIdLogo" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/>
</Relationships>`;
}

function spreadsheetLogoRelationships() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rIdLogo" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/chemvault-logo.png"/>
</Relationships>`;
}

function spreadsheetLogoDrawing() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <xdr:twoCellAnchor editAs="oneCell">
    <xdr:from><xdr:col>3</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>0</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from>
    <xdr:to><xdr:col>5</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>5</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>
    <xdr:pic>
      <xdr:nvPicPr><xdr:cNvPr id="2" name="ChemVault logo" descr="ChemVault"/><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr>
      <xdr:blipFill><a:blip r:embed="rIdLogo"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill>
      <xdr:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="1219200" cy="1219200"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr>
    </xdr:pic>
    <xdr:clientData/>
  </xdr:twoCellAnchor>
</xdr:wsDr>`;
}

function coreProperties(generatedAt: Date) {
  const stamp = generatedAt.toISOString();
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>${escapeXml(CHEMVAULT_TITLE)}</dc:title>
  <dc:subject>${escapeXml(CHEMVAULT_SUBJECT)}</dc:subject>
  <dc:creator>${escapeXml(CHEMVAULT_AUTHOR)}</dc:creator>
  <dc:rights>${escapeXml(CHEMVAULT_COPYRIGHT_NOTICE)}</dc:rights>
  <cp:keywords>${escapeXml(CHEMVAULT_KEYWORDS)}</cp:keywords>
  <dc:description>${escapeXml(CHEMVAULT_SUBJECT)}</dc:description>
  <cp:lastModifiedBy>${escapeXml(CHEMVAULT_CREATOR)}</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">${stamp}</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">${stamp}</dcterms:modified>
</cp:coreProperties>`;
}

function appProperties(application: string) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>${escapeXml(application)}</Application>
  <Company>${escapeXml(CHEMVAULT_COMPANY)}</Company>
  <Manager>${escapeXml(CHEMVAULT_CREATOR)}</Manager>
</Properties>`;
}

function customProperties() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="Copyright"><vt:lpwstr>${escapeXml(CHEMVAULT_COPYRIGHT_NOTICE)}</vt:lpwstr></property>
  <property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="3" name="GeneratedBy"><vt:lpwstr>${escapeXml(CHEMVAULT_CREATOR)}</vt:lpwstr></property>
</Properties>`;
}

function wordSettings() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:updateFields w:val="true"/>
</w:settings>`;
}

function wordStyles() {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Footer"><w:name w:val="footer"/><w:basedOn w:val="Normal"/><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr></w:style>
</w:styles>`;
}

function wordFooter(hasBrandLogo = false) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
  <w:p>
    <w:pPr>
      <w:pStyle w:val="Footer"/>
      <w:tabs><w:tab w:val="right" w:pos="9360"/></w:tabs>
      <w:pBdr><w:top w:val="single" w:sz="4" w:space="8" w:color="CBD5E1"/></w:pBdr>
    </w:pPr>
    ${hasBrandLogo ? wordLogoRun() : ''}
    <w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:t>${escapeXml(CHEMVAULT_COPYRIGHT_NOTICE)}</w:t></w:r>
    <w:r><w:tab/></w:r>
    <w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:t>Page </w:t></w:r>
    ${wordField('PAGE', '1')}
    <w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:t> of </w:t></w:r>
    ${wordField('NUMPAGES', '1')}
  </w:p>
</w:ftr>`;
}

function wordLogoRun() {
  return `<w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0">
    <wp:extent cx="182880" cy="182880"/><wp:effectExtent l="0" t="0" r="0" b="0"/>
    <wp:docPr id="1" name="ChemVault logo" descr="ChemVault"/>
    <wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr>
    <a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
      <pic:pic>
        <pic:nvPicPr><pic:cNvPr id="1" name="ChemVault logo"/><pic:cNvPicPr/></pic:nvPicPr>
        <pic:blipFill><a:blip r:embed="rIdLogo"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill>
        <pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="182880" cy="182880"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr>
      </pic:pic>
    </a:graphicData></a:graphic>
  </wp:inline></w:drawing></w:r><w:r><w:t xml:space="preserve">  </w:t></w:r>`;
}

function wordField(instruction: string, fallback: string) {
  return [
    '<w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:fldChar w:fldCharType="begin"/></w:r>',
    `<w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:instrText xml:space="preserve"> ${escapeXml(instruction)} </w:instrText></w:r>`,
    '<w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:fldChar w:fldCharType="separate"/></w:r>',
    `<w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:t>${escapeXml(fallback)}</w:t></w:r>`,
    '<w:r><w:rPr><w:color w:val="64748B"/><w:sz w:val="16"/></w:rPr><w:fldChar w:fldCharType="end"/></w:r>'
  ].join('');
}

export function createZip(entries: ZipEntry[]) {
  const localParts: Uint8Array[] = [];
  const centralParts: Uint8Array[] = [];
  let offset = 0;

  entries.forEach((entry) => {
    const nameBytes = TEXT_ENCODER.encode(entry.path);
    const data = typeof entry.content === 'string' ? TEXT_ENCODER.encode(entry.content) : entry.content;
    const crc = crc32(data);
    const { date, time } = dosDateTime(new Date());
    const localHeader = new Uint8Array(30 + nameBytes.length);
    const localView = new DataView(localHeader.buffer);
    localView.setUint32(0, 0x04034b50, true);
    localView.setUint16(4, 20, true);
    localView.setUint16(6, 0x0800, true);
    localView.setUint16(8, 0, true);
    localView.setUint16(10, time, true);
    localView.setUint16(12, date, true);
    localView.setUint32(14, crc, true);
    localView.setUint32(18, data.length, true);
    localView.setUint32(22, data.length, true);
    localView.setUint16(26, nameBytes.length, true);
    localHeader.set(nameBytes, 30);
    localParts.push(localHeader, data);

    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const centralView = new DataView(centralHeader.buffer);
    centralView.setUint32(0, 0x02014b50, true);
    centralView.setUint16(4, 20, true);
    centralView.setUint16(6, 20, true);
    centralView.setUint16(8, 0x0800, true);
    centralView.setUint16(10, 0, true);
    centralView.setUint16(12, time, true);
    centralView.setUint16(14, date, true);
    centralView.setUint32(16, crc, true);
    centralView.setUint32(20, data.length, true);
    centralView.setUint32(24, data.length, true);
    centralView.setUint16(28, nameBytes.length, true);
    centralView.setUint32(42, offset, true);
    centralHeader.set(nameBytes, 46);
    centralParts.push(centralHeader);

    offset += localHeader.length + data.length;
  });

  const centralDirectory = concatBytes(centralParts);
  const end = new Uint8Array(22);
  const endView = new DataView(end.buffer);
  endView.setUint32(0, 0x06054b50, true);
  endView.setUint16(8, entries.length, true);
  endView.setUint16(10, entries.length, true);
  endView.setUint32(12, centralDirectory.length, true);
  endView.setUint32(16, offset, true);

  return concatBytes([...localParts, centralDirectory, end]);
}

function concatBytes(parts: Uint8Array[]) {
  const totalLength = parts.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(totalLength);
  let offset = 0;
  parts.forEach((part) => {
    output.set(part, offset);
    offset += part.length;
  });
  return output;
}

function dosDateTime(dateValue: Date) {
  const year = Math.max(1980, dateValue.getFullYear());
  const date = ((year - 1980) << 9) | ((dateValue.getMonth() + 1) << 5) | dateValue.getDate();
  const time = (dateValue.getHours() << 11) | (dateValue.getMinutes() << 5) | Math.floor(dateValue.getSeconds() / 2);
  return { date, time };
}

const CRC_TABLE = Array.from({ length: 256 }, (_, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) {
    value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  }
  return value >>> 0;
});

function crc32(data: Uint8Array) {
  let crc = 0xffffffff;
  data.forEach((byte) => {
    crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  });
  return (crc ^ 0xffffffff) >>> 0;
}

function parsePdfPng(bytes: Uint8Array): PdfPngImage | null {
  const signature = [137, 80, 78, 71, 13, 10, 26, 10];
  if (bytes.length < 33 || signature.some((value, index) => bytes[index] !== value)) return null;

  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const width = view.getUint32(16, false);
  const height = view.getUint32(20, false);
  const bitDepth = bytes[24];
  const colorType = bytes[25];
  const interlace = bytes[28];
  if (!width || !height || bitDepth !== 8 || colorType !== 2 || interlace !== 0) return null;

  const idatChunks: Uint8Array[] = [];
  let offset = 8;
  while (offset + 12 <= bytes.length) {
    const length = view.getUint32(offset, false);
    const typeOffset = offset + 4;
    const dataOffset = offset + 8;
    const nextOffset = dataOffset + length + 4;
    if (nextOffset > bytes.length) return null;
    const type = String.fromCharCode(bytes[typeOffset], bytes[typeOffset + 1], bytes[typeOffset + 2], bytes[typeOffset + 3]);
    if (type === 'IDAT') idatChunks.push(bytes.slice(dataOffset, dataOffset + length));
    if (type === 'IEND') break;
    offset = nextOffset;
  }

  if (!idatChunks.length) return null;
  return { compressedData: concatBytes(idatChunks), height, width };
}

function pdfPngImageObject(image: PdfPngImage) {
  const header = TEXT_ENCODER.encode(
    `<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /DecodeParms << /Predictor 15 /Colors 3 /BitsPerComponent 8 /Columns ${image.width} >> /Length ${image.compressedData.length} >>\nstream\n`
  );
  return concatBytes([header, image.compressedData, TEXT_ENCODER.encode('\nendstream')]);
}

function buildPdf(objects: PdfObject[], infoObjectId: number) {
  const parts: Uint8Array[] = [TEXT_ENCODER.encode('%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n')];
  const offsets = [0];
  let currentOffset = parts[0].length;
  objects.forEach((object, index) => {
    offsets.push(currentOffset);
    const prefix = TEXT_ENCODER.encode(`${index + 1} 0 obj\n`);
    const body = typeof object === 'string' ? TEXT_ENCODER.encode(object) : object;
    const suffix = TEXT_ENCODER.encode('\nendobj\n');
    parts.push(prefix, body, suffix);
    currentOffset += prefix.length + body.length + suffix.length;
  });
  const xrefOffset = currentOffset;
  parts.push(TEXT_ENCODER.encode(`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`));
  offsets.slice(1).forEach((offset) => {
    parts.push(TEXT_ENCODER.encode(`${String(offset).padStart(10, '0')} 00000 n \n`));
  });
  parts.push(TEXT_ENCODER.encode(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info ${infoObjectId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`));
  return concatBytes(parts);
}

function pdfDate(value: Date) {
  const pad = (number: number) => String(number).padStart(2, '0');
  return `D:${value.getUTCFullYear()}${pad(value.getUTCMonth() + 1)}${pad(value.getUTCDate())}${pad(value.getUTCHours())}${pad(value.getUTCMinutes())}${pad(value.getUTCSeconds())}Z`;
}

function byteLength(value: string) {
  return TEXT_ENCODER.encode(value).length;
}

function escapeXml(value: string | number) {
  return sanitizeXmlText(String(value))
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function sanitizeXmlText(value: string) {
  return value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f\ud800-\udfff]/gu, '');
}

function boundedLogLines(value: string) {
  const allLines = value.split(/\r?\n/u);
  const lines = allLines.slice(0, XLSX_MAX_LOG_ROWS);
  if (allLines.length > XLSX_MAX_LOG_ROWS) {
    lines.push('Log truncated for Excel export. Use Export Log for the complete text output.');
  }
  return lines;
}

function xlsxCellText(value: string) {
  const sanitized = sanitizeXmlText(String(value));
  if (sanitized.length <= XLSX_MAX_CELL_TEXT_LENGTH) return sanitized;
  return `${sanitized.slice(0, XLSX_MAX_CELL_TEXT_LENGTH - 80)} [truncated for Excel cell limit]`;
}

function sanitizePdfText(value: string) {
  return value.replace(/[^\x09\x0a\x0d\x20-\x7e]/gu, '?');
}

function escapePdf(value: string) {
  return sanitizePdfText(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}
